AWSTemplateFormatVersion: '2010-09-09'
Description: 'Personal Website Infrastructure for jpagan.com'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'jpagan-personal'
    Description: 'Environment name for resources'

Resources:
  # S3 Bucket for website content
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: jpagan-personal-website
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET]
            AllowedOrigins: ['*']
            MaxAge: 3000

  # Bucket policy to make it publicly readable
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${WebsiteBucket}/*'

  # SSL Certificate
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: jpagan.com
      SubjectAlternativeNames:
        - www.jpagan.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: jpagan.com
          HostedZoneId: Z08377472TTB9WSCI997G
        - DomainName: www.jpagan.com
          HostedZoneId: Z08377472TTB9WSCI997G

  # CloudFront distribution
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        Aliases:
          - jpagan.com
          - www.jpagan.com
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # Route53 record for jpagan.com
  WebsiteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z08377472TTB9WSCI997G
      Name: jpagan.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

  # Route53 record for www.jpagan.com
  WWWWebsiteRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z08377472TTB9WSCI997G
      Name: www.jpagan.com
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
        EvaluateTargetHealth: false

Outputs:
  WebsiteBucketName:
    Description: 'Name of the S3 bucket for website content'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucket'

  CloudFrontDistributionId:
    Description: 'CloudFront distribution ID'
    Value: !Ref WebsiteDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'

  CloudFrontDomainName:
    Description: 'CloudFront distribution domain name'
    Value: !GetAtt WebsiteDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
