# Generated by Django 4.2.23 on 2025-08-21 23:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("orig_filename", models.CharField(max_length=255)),
                ("storage_path", models.CharField(max_length=500)),
                ("mime_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_videoasset",
            },
        ),
    ]
