# Generated by Django 4.2.23 on 2025-08-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoasset',
            options={'verbose_name': 'Video Asset', 'verbose_name_plural': 'Video Assets'},
        ),
        migrations.AddField(
            model_name='videoasset',
            name='access_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this asset was accessed'),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='is_valid',
            field=models.BooleanField(default=True, help_text='Whether the asset passed integrity checks'),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='last_accessed',
            field=models.DateTimeField(blank=True, help_text='Last time this asset was accessed', null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='last_validated',
            field=models.DateTimeField(blank=True, help_text='When the asset was last validated', null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed', null=True),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status of the video', max_length=20),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the asset was last updated'),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='List of validation errors found'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='checksum_sha256',
            field=models.CharField(help_text='SHA256 checksum for integrity verification', max_length=64),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the asset was created'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='duration_sec',
            field=models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='mime_type',
            field=models.CharField(help_text='MIME type of the video', max_length=100),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='orig_filename',
            field=models.CharField(help_text='Original filename as uploaded', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='poster_path',
            field=models.CharField(blank=True, help_text='Path to video poster image', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='size_bytes',
            field=models.PositiveIntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='storage_path',
            field=models.CharField(help_text='Full path to stored video file', max_length=500),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['mime_type'], name='core_videoa_mime_ty_49a7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['processing_status'], name='core_videoa_process_ca73a2_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['created_at'], name='core_videoa_created_4c152f_idx'),
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['is_valid'], name='core_videoa_is_vali_a570d9_idx'),
        ),
    ]
