# Generated by Django 4.2.23 on 2025-08-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_videoasset_options_videoasset_access_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videoasset',
            name='core_videoa_is_vali_a570d9_idx',
        ),
    ]
