# Generated by Django 4.2.23 on 2025-08-30 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250830_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clip_hash', models.CharField(help_text='SHA256 hash of clip selection for idempotency', max_length=64, unique=True)),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('storage_path', models.CharField(help_text='Path to cropped video file', max_length=500)),
                ('size_bytes', models.PositiveIntegerField(help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status of the clip', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the clip was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the clip was last updated')),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='core.videoasset')),
            ],
            options={
                'verbose_name': 'Video Clip',
                'verbose_name_plural': 'Video Clips',
                'db_table': 'core_videoclip',
                'indexes': [models.Index(fields=['clip_hash'], name='core_videoc_clip_ha_6c5a44_idx'), models.Index(fields=['original_video', 'start_time', 'end_time'], name='core_videoc_origina_ed8c17_idx'), models.Index(fields=['processing_status'], name='core_videoc_process_90d3f6_idx'), models.Index(fields=['created_at'], name='core_videoc_created_6de2e0_idx')],
            },
        ),
    ]
