# Generated by Django 4.2.23 on 2025-08-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videoclip'),
    ]

    operations = [
    ]
