# Generated by Django 4.2.23 on 2025-08-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250830_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
    ]
