# Generated by Django 4.2.23 on 2025-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_videoclip_size_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='video_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('recorded', 'Recorded'), ('youtube', 'YouTube')], default='upload', help_text='Type of video source', max_length=20),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='checksum_sha256',
            field=models.CharField(blank=True, help_text='SHA256 checksum for integrity verification', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='storage_path',
            field=models.CharField(blank=True, help_text='Full path to stored video file', max_length=500, null=True),
        ),
    ]
