# Generated by Django 4.2.7 on 2025-09-06 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisevideo',
            name='time_of_day',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of day when this exercise was practiced'),
        ),
        migrations.AddField(
            model_name='practicethread',
            name='time_of_day',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time of day when this practice session occurred'),
        ),
    ]
