# Generated by Django 4.2.7 on 2025-09-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_exercisevideo_time_of_day_practicethread_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisevideo',
            name='time_of_day',
            field=models.TimeField(auto_now_add=True, help_text='Time of day when this exercise was practiced'),
        ),
        migrations.AlterField(
            model_name='practicethread',
            name='time_of_day',
            field=models.TimeField(auto_now_add=True, help_text='Time of day when this practice session occurred'),
        ),
    ]
