# Generated by Django 6.0.2 on 2026-02-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_sessionlastseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='videos.tag'),
        ),
    ]
