# Generated by Django 6.0.2 on 2026-02-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_space_invitecode_space_session_space_spacemember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='space',
            name='invite_slug',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
