# Generated by Django 6.0.2 on 2026-03-17 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_review_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('practice_minutes', models.PositiveIntegerField(default=0)),
                ('comments_received', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CoachDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_students_30d', models.PositiveIntegerField(default=0)),
                ('coach_comments_7d', models.PositiveIntegerField(default=0)),
                ('coach_comments_30d', models.PositiveIntegerField(default=0)),
                ('median_time_to_first_coach_comment_hours_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_time_saved_hours_30d', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CoachEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_uploaded', 'Session Uploaded'), ('feedback_requested', 'Feedback Requested'), ('feedback_claimed', 'Feedback Claimed'), ('feedback_completed', 'Feedback Completed'), ('video_feedback_completed', 'Video Feedback Completed')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='multipartsessionupload',
            new_name='videos_mult_user_id_c16210_idx',
            old_name='videos_multi_user_id_62daca_idx',
        ),
        migrations.RenameIndex(
            model_name='multipartsessionupload',
            new_name='videos_mult_expires_4ae082_idx',
            old_name='videos_multi_expires_dbb13d_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('coach', 'Coach'), ('admin', 'Admin')], default='student', max_length=16),
        ),
        migrations.AddField(
            model_name='reviewlink',
            name='pin_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='session',
            name='playback_hls_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='playback_mp4_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='source_video_object_key',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upload_in_progress', 'Upload in Progress'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='session',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='multipartsessionupload',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('aborted', 'Aborted'), ('expired', 'Expired')], default='initiated', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewfeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='processing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upload_in_progress', 'Upload in Progress'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=24),
        ),
        migrations.AddField(
            model_name='analyticsdaily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_daily', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachdailymetric',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_daily_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_events', to='videos.session'),
        ),
        migrations.AddField(
            model_name='coachevent',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_events', to='videos.space'),
        ),
        migrations.AddField(
            model_name='coachevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsdaily',
            index=models.Index(fields=['user', 'date'], name='analytics_daily_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdaily',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='analytics_daily_user_date_uniq'),
        ),
        migrations.AddIndex(
            model_name='coachdailymetric',
            index=models.Index(fields=['coach', 'date'], name='coach_daily_metric_cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='coachdailymetric',
            constraint=models.UniqueConstraint(fields=('coach', 'date'), name='coach_daily_metric_cd_uniq'),
        ),
        migrations.AddIndex(
            model_name='coachevent',
            index=models.Index(fields=['user', 'event_type', 'occurred_at'], name='coach_event_user_type_time_idx'),
        ),
    ]
