# Generated by Django 6.0.3 on 2026-03-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_rename_comments_to_video_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(max_length=64)),
                ('student_level', models.CharField(blank=True, max_length=64)),
                ('goal', models.CharField(max_length=255)),
                ('exercise_or_song', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('requested_turnaround_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('opened', 'Opened'), ('responded', 'Responded'), ('viewed', 'Viewed'), ('resubmitted', 'Resubmitted'), ('closed', 'Closed'), ('revoked', 'Revoked')], default='requested', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['teacher_id', 'student_id'],
            },
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_review_requests_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='review_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_request', to='videos.reviewlink'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests', to='videos.session'),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherrostermembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherrostermembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherrostermembership',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['teacher', 'status'], name='videos_revi_teacher_ef8574_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['student', 'status'], name='videos_revi_student_a39225_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherrostermembership',
            constraint=models.UniqueConstraint(fields=('teacher', 'student'), name='teacher_roster_membership_teacher_student_uniq'),
        ),
    ]
