# Generated by Django 6.0.3 on 2026-03-20 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_reviewrequest_teacherrostermembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='videofeedback',
            name='review_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='videos.reviewrequest'),
        ),
        migrations.AddField(
            model_name='feedbacktemplate',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='feedbacktemplate',
            constraint=models.UniqueConstraint(fields=('teacher', 'title'), name='feedback_template_teacher_title_uniq'),
        ),
    ]
