# Generated by Django 6.0.3 on 2026-03-20 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_feedbacktemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='parent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_requests', to='videos.reviewrequest'),
        ),
    ]
