# Generated by Django 6.0.3 on 2026-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_rename_videos_multi_user_id_62daca_idx_videos_mult_user_id_c16210_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofeedback',
            name='feedback_category',
            field=models.CharField(blank=True, choices=[('timing', 'Timing'), ('groove', 'Groove'), ('dynamics', 'Dynamics'), ('technique', 'Technique'), ('posture', 'Posture'), ('tone', 'Tone')], max_length=24),
        ),
    ]
