# Generated by Codex on 2026-04-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0033_session_user_recorded_at_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherrostermembership',
            name='teacher_roster_membership_teacher_student_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='feedbacktemplate',
            name='feedback_template_teacher_title_uniq',
        ),
        migrations.RemoveIndex(
            model_name='reviewrequest',
            name='videos_revi_teacher_ef8574_idx',
        ),
        migrations.RenameModel(
            old_name='TeacherRosterMembership',
            new_name='ReviewerRosterMembership',
        ),
        migrations.RenameField(
            model_name='reviewrequest',
            old_name='teacher',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='reviewerrostermembership',
            old_name='teacher',
            new_name='reviewer',
        ),
        migrations.RenameField(
            model_name='feedbacktemplate',
            old_name='teacher',
            new_name='reviewer',
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_requests_as_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewerrostermembership',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reviewerrostermembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviewer_roster_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='reviewerrostermembership',
            options={'ordering': ['reviewer_id', 'student_id']},
        ),
        migrations.AddConstraint(
            model_name='reviewerrostermembership',
            constraint=models.UniqueConstraint(fields=('reviewer', 'student'), name='reviewer_roster_membership_reviewer_student_uniq'),
        ),
        migrations.AddConstraint(
            model_name='feedbacktemplate',
            constraint=models.UniqueConstraint(fields=('reviewer', 'title'), name='feedback_template_reviewer_title_uniq'),
        ),
        migrations.AddIndex(
            model_name='reviewrequest',
            index=models.Index(fields=['reviewer', 'status'], name='videos_revi_reviewe_cca2f2_idx'),
        ),
    ]
