# Generated by Codex on 2026-04-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_reviewer_schema_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='status_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='status_reason',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('opened', 'Opened'), ('responded', 'Responded'), ('viewed', 'Viewed'), ('needs_resubmission', 'Needs Resubmission'), ('declined_unrelated', 'Declined Unrelated'), ('flagged', 'Flagged'), ('resubmitted', 'Resubmitted'), ('closed', 'Closed'), ('revoked', 'Revoked')], default='requested', max_length=24),
        ),
        migrations.CreateModel(
            name='ReviewRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('status_changed', 'Status Changed'), ('responded', 'Responded'), ('viewed', 'Viewed')], max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_request_events', to=settings.AUTH_USER_MODEL)),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='videos.reviewrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reviewrequestevent',
            index=models.Index(fields=['review_request', 'created_at'], name='videos_revi_review__d80ba2_idx'),
        ),
    ]
