# Generated by Django 6.0.3 on 2026-04-11 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0035_reviewrequest_loop_and_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('intent', models.CharField(choices=[('lightweight_review', 'Lightweight Review'), ('roster_join', 'Roster Join')], default='lightweight_review', max_length=24)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_reviewer_invites', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviewer_invites', to=settings.AUTH_USER_MODEL)),
                ('invite_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_invite', to='videos.signupinvitecode')),
                ('review_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_invites', to='videos.reviewlink')),
                ('review_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_invites', to='videos.reviewrequest')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_invites', to='videos.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
