# Generated by Django 6.0.3 on 2026-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_session_client_upload_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='multipartsessionupload',
            new_name='videos_mult_user_id_c16210_idx',
            old_name='videos_multi_user_id_62daca_idx',
        ),
        migrations.RenameIndex(
            model_name='multipartsessionupload',
            new_name='videos_mult_expires_4ae082_idx',
            old_name='videos_multi_expires_dbb13d_idx',
        ),
        migrations.RenameIndex(
            model_name='producteventlog',
            new_name='videos_prod_event_n_ce9c2c_idx',
            old_name='videos_produ_event_n_2ae9b2_idx',
        ),
        migrations.RenameIndex(
            model_name='session',
            new_name='videos_sess_user_id_15a77a_idx',
            old_name='videos_sess_user_recorded_idx',
        ),
        migrations.AlterField(
            model_name='reviewlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewrequestevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('status_changed', 'Status Changed'), ('responded', 'Responded'), ('viewed', 'Viewed'), ('thread_renamed', 'Thread Renamed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='videofeedback',
            name='feedback_video',
            field=models.FileField(blank=True, null=True, upload_to='feedback_videos/'),
        ),
    ]
