# Generated by Django 6.0.3 on 2026-07-12 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0043_skillsharelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofChallengeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='proofchallengeresponse',
            name='challenge_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_responses', to='videos.reviewlink'),
        ),
        migrations.AddField(
            model_name='proofchallengeresponse',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_challenge_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proofchallengeresponse',
            name='response_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_response_submission', to='videos.session'),
        ),
        migrations.AddField(
            model_name='proofchallengeresponse',
            name='source_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_responses_received', to='videos.session'),
        ),
        migrations.AddIndex(
            model_name='proofchallengeresponse',
            index=models.Index(fields=['source_session', 'created_at'], name='challenge_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='proofchallengeresponse',
            index=models.Index(fields=['responder', 'created_at'], name='challenge_resp_created_idx'),
        ),
    ]
