# Generated by Django 6.0.3 on 2026-07-18 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0044_proof_challenge_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionProofResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('metric_name', models.CharField(blank=True, max_length=120)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_unit', models.CharField(blank=True, max_length=40)),
                ('ranking_direction', models.CharField(choices=[('higher', 'Higher is better'), ('lower', 'Lower is better'), ('rated', 'Rated')], default='higher', max_length=16)),
                ('source', models.CharField(choices=[('self', 'Self'), ('peer', 'Peer'), ('reviewer', 'Reviewer'), ('ai', 'AI')], default='self', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['drill_name', 'metric_name', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='sessionproofresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_result', to='videos.session'),
        ),
        migrations.AddIndex(
            model_name='sessionproofresult',
            index=models.Index(fields=['drill_name', 'metric_name'], name='videos_sess_drill_n_3c99d0_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionproofresult',
            index=models.Index(fields=['ranking_direction'], name='videos_sess_ranking_1327d6_idx'),
        ),
    ]
