# Generated by Django 6.0.3 on 2026-09-16 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_sessionproofresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('meal', 'Meal'), ('recipe', 'Recipe'), ('lesson_note', 'Lesson note'), ('fitness', 'Fitness'), ('habit', 'Habit'), ('therapy', 'Therapy'), ('class_note', 'Class note')], db_index=True, default='habit', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metric_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='journal_entries', to='videos.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='journal_attachments/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=16)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='videos.journalentry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('purpose', models.TextField(blank=True)),
                ('learned_from', models.CharField(blank=True, max_length=160)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_today', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='videos.routine'),
        ),
        migrations.CreateModel(
            name='RoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('default_unit', models.CharField(blank=True, max_length=40)),
                ('default_target_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='videos.routine')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='routine_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='videos.routineitem'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'is_active'], name='videos_rout_user_id_ea5132_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'category'], name='videos_rout_user_id_6d75fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='routine_user_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_today', True)), fields=('user',), name='routine_one_today_per_user'),
        ),
        migrations.AddConstraint(
            model_name='routineitem',
            constraint=models.UniqueConstraint(fields=('routine', 'name'), name='routine_item_routine_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'occurred_at'], name='videos_jour_user_id_203f12_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'entry_type', 'occurred_at'], name='videos_jour_user_id_06ec3f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'category', 'occurred_at'], name='videos_jour_user_id_0fdc34_idx'),
        ),
    ]
