# Generated by Django 4.2.23 on 2025-08-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocomment',
            options={'ordering': ['-created_at']},
        ),
    ]
