# Generated by Django 4.2.23 on 2025-08-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_videoasset_core_videoa_is_vali_a570d9_idx'),
        ('comments', '0002_alter_videocomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.videoasset'),
        ),
    ]
