# Generated by Django 4.2.23 on 2025-08-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_videocomment_video_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='video_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.videoasset'),
        ),
    ]
