# Generated by Django 4.2.23 on 2025-08-26 20:39

from django.db import migrations, models
import django.db.models.deletion


def delete_comments_without_video(apps, schema_editor):
    """Delete any existing comments that don't have a video_asset"""
    VideoComment = apps.get_model('comments', 'VideoComment')
    # Delete comments without video_asset (these shouldn't exist in production)
    VideoComment.objects.filter(video_asset__isnull=True).delete()


def reverse_delete_comments(apps, schema_editor):
    """Reverse operation - nothing to do since we deleted the comments"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20250826_1943'),
    ]

    operations = [
        # First, delete any comments without video_asset
        migrations.RunPython(delete_comments_without_video, reverse_delete_comments),
        
        # Then make video_asset non-nullable
        migrations.AlterField(
            model_name='videocomment',
            name='video_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videoasset'),
        ),
    ]
