# Generated by Django 5.2.5 on 2025-08-28 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_auto_20250826_2039"),
        ("core", "0004_videoasset_renditions"),
        ("exercises", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["exercise"], name="comments_vi_exercis_e517c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["author"], name="comments_vi_author__90d7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videocomment",
            index=models.Index(
                fields=["created_at"], name="comments_vi_created_653527_idx"
            ),
        ),
    ]
