# Generated by Django 5.2.5 on 2025-08-26 23:53

from django.db import migrations


def seed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.bulk_create([
        Role(name="student"),
        Role(name="instructor"),
    ])


def unseed_roles(apps, schema_editor):
    Role = apps.get_model("accounts", "Role")
    Role.objects.filter(name__in=["student", "instructor"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_roles, unseed_roles)
    ]
