# Generated by Django 4.2.23 on 2025-08-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250827_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
