# Generated by Django 5.2.5 on 2025-08-28 05:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_comments_made_profile_exercises_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "token",
                    models.CharField(
                        default=accounts.models._generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
