# Generated by Django 5.2.5 on 2025-08-28 05:30

"""Migration to move user metrics to dedicated model."""

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    UserMetrics = apps.get_model("accounts", "UserMetrics")
    for profile in Profile.objects.all():
        UserMetrics.objects.create(
            profile=profile,
            exercises_created=profile.exercises_created,
            comments_made=profile.comments_made,
            total_video_time=profile.total_video_time,
        )


def backwards(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    UserMetrics = apps.get_model("accounts", "UserMetrics")
    for metrics in UserMetrics.objects.all():
        profile = metrics.profile
        profile.exercises_created = metrics.exercises_created
        profile.comments_made = metrics.comments_made
        profile.total_video_time = metrics.total_video_time
        profile.save(
            update_fields=["exercises_created", "comments_made", "total_video_time"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_comments_made_profile_exercises_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercises_created", models.PositiveIntegerField(default=0)),
                ("comments_made", models.PositiveIntegerField(default=0)),
                ("total_video_time", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="profile",
            name="comments_made",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="exercises_created",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="total_video_time",
        ),
    ]
