# Generated by Django 4.2.23 on 2025-08-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_betainvitation'),
        ('accounts', '0006_remove_profile_comments_made_and_more'),
    ]

    operations = [
    ]
