# Generated by Django 4.2.23 on 2025-09-02 02:25

import apps.videos.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file', models.FileField(upload_to=apps.videos.models.video_upload_path)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, help_text='Trust score based on metadata accuracy (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playlists.playlist')),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['created_at'],
            },
        ),
    ]
