# Generated by Django 5.2.5 on 2025-08-28 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_videoasset_renditions"),
        ("exercises", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["created_by"], name="exercises_e_created_67ada7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["created_at"], name="exercises_e_created_2a660d_idx"
            ),
        ),
    ]
