"""
Django settings for practika_project project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import logging.config
from pathlib import Path
from datetime import timedelta

# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment detection
ENVIRONMENT = os.getenv('DJANGO_ENVIRONMENT', 'development')
IS_PRODUCTION = ENVIRONMENT == 'production'
IS_DEVELOPMENT = ENVIRONMENT == 'development'
IS_TESTING = ENVIRONMENT == 'testing'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', "django-insecure-^mso&+&9%q-5cj+)jedf%rn9%geu4m#$v5mpk=9k^xt1^z5yn#")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true' and not IS_PRODUCTION

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION

# Enhanced security for development
if IS_DEVELOPMENT:
    # Session security
    SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True
    SESSION_COOKIE_AGE = 3600  # 1 hour
    
    # CSRF security
    CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_USE_SESSIONS = True
    
    # Additional security headers
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Rate limiting settings
    RATE_LIMIT_ENABLED = True
    LOGIN_RATE_LIMIT = '5/minute'  # 5 attempts per minute
    UPLOAD_RATE_LIMIT = '10/minute'  # 10 uploads per minute
    
    # Security logging
    SECURITY_LOGGING_ENABLED = True
    FAILED_LOGIN_ATTEMPTS_LIMIT = 5
    ACCOUNT_LOCKOUT_DURATION = 300  # 5 minutes

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "core",
    "exercises",
    "comments",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add WhiteNoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.RequestLoggingMiddleware",
    "core.middleware.PerformanceMonitoringMiddleware",
    "core.middleware.SecurityMiddleware",
    "core.middleware.MobileOptimizationMiddleware",  # Mobile optimization middleware
]

ROOT_URLCONF = "practika_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "practika_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv('DJANGO_DB_ENGINE', 'django.db.backends.sqlite3'),
        "NAME": os.getenv('DJANGO_DB_NAME', BASE_DIR / "db.sqlite3"),
        "USER": os.getenv('DJANGO_DB_USER', ''),
        "PASSWORD": os.getenv('DJANGO_DB_PASSWORD', ''),
        "HOST": os.getenv('DJANGO_DB_HOST', ''),
        "PORT": os.getenv('DJANGO_DB_PORT', ''),
        "OPTIONS": {
            "timeout": 20,
            "check_same_thread": False,
        } if os.getenv('DJANGO_DB_ENGINE', '').endswith('sqlite3') else {},
    }
}

# Database connection pooling and optimization
if not IS_DEVELOPMENT:
    DATABASES['default']['CONN_MAX_AGE'] = 600
    DATABASES['default']['OPTIONS']['MAX_CONNS'] = 20

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# WhiteNoise configuration for static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Enable WhiteNoise compression and caching
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour"
    },
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DJANGO_FILE_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DJANGO_DATA_UPLOAD_MAX_MEMORY_SIZE', 100 * 1024 * 1024))  # 100MB
FILE_UPLOAD_TEMP_DIR = os.getenv('DJANGO_FILE_UPLOAD_TEMP_DIR', None)

# CORS settings
CORS_ALLOWED_ORIGINS = os.getenv('DJANGO_CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CORS_ALLOW_CREDENTIALS = True

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache" if not IS_DEVELOPMENT else "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": os.getenv('DJANGO_REDIS_URL', '127.0.0.1:6379/1'),
        "OPTIONS": {
            "CLIENT_CLASS": "redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "ssl_cert_reqs": None,  # Disable SSL certificate verification for Heroku Redis
                "ssl": True,
            } if not IS_DEVELOPMENT else {},
        } if not IS_DEVELOPMENT else {},
        "TIMEOUT": 300,
        "KEY_PREFIX": "practika",
    }
}

# Logging configuration
LOGGING_CONFIG = None

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s", "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s", "line": "%(lineno)d"}',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'error.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'] if DEBUG else [],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'exercises': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'comments': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Initialize logging
# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Initialize logging after directory creation
logging.config.dictConfig(LOGGING)

# Performance monitoring
PERFORMANCE_MONITORING = {
    'ENABLED': os.getenv('DJANGO_PERFORMANCE_MONITORING', 'True').lower() == 'true',
    'SLOW_QUERY_THRESHOLD': float(os.getenv('DJANGO_SLOW_QUERY_THRESHOLD', 1.0)),  # seconds
    'LOG_SLOW_QUERIES': True,
    'LOG_MEMORY_USAGE': True,
}

# Health check settings
HEALTH_CHECK = {
    'ENABLED': True,
    'DATABASE_CHECK': True,
    'CACHE_CHECK': True,
    'STORAGE_CHECK': True,
}

# API Documentation
API_DOCUMENTATION = {
    'ENABLED': True,
    'TITLE': 'Practika API',
    'DESCRIPTION': 'Learning Management System API',
    'VERSION': '1.0.0',
}

# Rate limiting
RATE_LIMITING = {
    'ENABLED': True,
    'DEFAULT_RATE': '100/hour',
    'BURST_RATE': '200/hour',
}

# Security headers
SECURITY_HEADERS = {
    'X_CONTENT_TYPE_OPTIONS': 'nosniff',
    'X_FRAME_OPTIONS': 'DENY',
    'X_XSS_PROTECTION': '1; mode=block',
    'STRICT_TRANSPORT_SECURITY': 'max-age=31536000; includeSubDomains' if IS_PRODUCTION else None,
}

# Monitoring and metrics
METRICS = {
    'ENABLED': True,
    'PROMETHEUS_ENABLED': os.getenv('DJANGO_PROMETHEUS_ENABLED', 'False').lower() == 'true',
    'HEALTH_CHECK_ENDPOINT': '/health/',
    'METRICS_ENDPOINT': '/metrics/',
}

# Mobile optimization settings
MOBILE_OPTIMIZATION = {
    'ENABLED': os.getenv('MOBILE_OPTIMIZATION_ENABLED', 'True').lower() == 'true',
    'PWA_ENABLED': os.getenv('PWA_ENABLED', 'True').lower() == 'true',
    'VIDEO_COMPRESSION_ENABLED': os.getenv('VIDEO_COMPRESSION_ENABLED', 'False').lower() == 'true',
    'CAMERA_QUALITY': os.getenv('MOBILE_CAMERA_QUALITY', '720p'),
    'MAX_RECORDING_TIME': int(os.getenv('MOBILE_MAX_RECORDING_TIME', 300)),
    'TOUCH_TARGET_SIZE': os.getenv('MOBILE_TOUCH_TARGET_SIZE', 'standard'),  # standard, medium, large
    'PERFORMANCE_MODE': os.getenv('MOBILE_PERFORMANCE_MODE', 'balanced'),  # conservative, balanced, optimized
}

# Log mobile optimization status
import logging
logger = logging.getLogger(__name__)
logger.info(f"Mobile optimization enabled: {MOBILE_OPTIMIZATION['ENABLED']}")
logger.info(f"PWA enabled: {MOBILE_OPTIMIZATION['PWA_ENABLED']}")
logger.info(f"Mobile camera quality: {MOBILE_OPTIMIZATION['CAMERA_QUALITY']}")
logger.info(f"Mobile max recording time: {MOBILE_OPTIMIZATION['MAX_RECORDING_TIME']} seconds")
